const SUPABASE_URL='https://bhqpixyiojthpfqnyhsh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_U2IRhs6K85S43ZRqKK5U8Q_HSknWMNY';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=(s,el=document)=>el.querySelector(s);const $$=(s,el=document)=>[...el.querySelectorAll(s)];
const state={session:null,user:null,profile:null,role:'none',dashboard:null,posts:[],editors:[],activeTab:'overview'};
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#039;','"':'&quot;'}[c]));
const fmt=d=>d?new Intl.DateTimeFormat('ro-RO',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d)):'—';
const imageUrl=path=>path?`${SUPABASE_URL}/storage/v1/object/public/blog-images/${String(path).split('/').map(encodeURIComponent).join('/')}`:'';
function toast(text,type=''){const el=$('#toast');el.textContent=text;el.className=`toast show ${type}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',3200);}
function setBusy(btn,busy,label='Se procesează…'){if(!btn)return;if(busy){btn.dataset.label=btn.textContent;btn.disabled=true;btn.textContent=label;}else{btn.disabled=false;btn.textContent=btn.dataset.label||btn.textContent;}}
function slugify(text=''){return String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,150)||'articol';}
async function currentSession(){const {data}=await db.auth.getSession();state.session=data.session;state.user=data.session?.user||null;return state.session;}
async function edge(name,payload={}){const s=await currentSession();if(!s?.access_token)throw new Error('Sesiunea a expirat. Intră din nou în cont.');const r=await fetch(`${SUPABASE_URL}/functions/v1/${name}`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_PUBLISHABLE_KEY,'Authorization':`Bearer ${s.access_token}`},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Operațiunea a eșuat.');return data;}
async function adminAction(action,payload={}){return edge('admin-api',{action,...payload});}

async function init(){
  let session=await currentSession();
  if(!session)return deny('Trebuie să fii autentificat în Support Hub pentru a deschide acest panou.');
  try{const refreshed=await db.auth.refreshSession();if(refreshed.data?.session){state.session=refreshed.data.session;state.user=refreshed.data.session.user;session=refreshed.data.session;}}catch(e){console.warn('refresh',e);}
  try{const access=await edge('admin-access',{});state.role=access.role||'none';}catch(e){console.error(e);return deny('Nu am putut verifica drepturile contului. Reîncarcă pagina sau autentifică-te din nou.');}
  if(state.role==='none')return deny('Acest cont nu are acces la panoul de administrare sau newsletter.');
  const {data:profile}=await db.from('profiles').select('display_name').eq('id',state.user.id).maybeSingle();state.profile=profile||null;
  $('#gate').hidden=true;$('#adminApp').hidden=false;$('#roleBadge').textContent=state.role==='admin'?'Administrator full':'Editor newsletter';
  $$('[data-admin-only]').forEach(el=>el.hidden=state.role!=='admin');
  bind();
  if(state.role==='admin'){state.activeTab='overview';await Promise.all([loadDashboard(),loadEditors(),loadPosts()]);}
  else{state.activeTab='newsletter';$('#newsletterRoleText').textContent='Ai acces editorial limitat: poți publica și edita propriile articole. Nu ai acces la utilizatori, raportări sau anunțuri.';await loadPosts();}
  showTab(state.activeTab);
}
function deny(message){$('#gate').innerHTML=`<h1>Acces indisponibil</h1><p>${esc(message)}</p><p><a class="back-link" href="/">Înapoi la Support Hub</a></p>`;}
function bind(){
  $$('.sidebar [data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
  $('#refreshDashboard').onclick=loadDashboard;
  $('#userSearch').oninput=renderUsers;$('#listingSearch').oninput=renderListings;
  $('#editorForm').onsubmit=addEditor;
  $('#postForm').onsubmit=savePost;$('#cancelPostEdit').onclick=resetPostForm;
  $('#postForm [name=image]').onchange=e=>previewLocalImage(e.target.files?.[0]);
}
function showTab(tab){state.activeTab=tab;$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==tab);$$('.sidebar [data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='newsletter')renderPosts();if(tab==='editors')renderEditors();}

async function loadDashboard(){
  if(state.role!=='admin')return;const btn=$('#refreshDashboard');setBusy(btn,true,'Se încarcă…');
  try{state.dashboard=await adminAction('dashboard');renderOverview();renderUsers();renderReports();renderListings();}catch(e){console.error(e);toast(e.message,'error');}finally{setBusy(btn,false);}
}
function renderOverview(){const d=state.dashboard;if(!d)return;const suspended=d.users.filter(u=>u.suspended).length,openReports=d.reports.filter(r=>r.status!=='resolved').length;$('#stats').innerHTML=`<div class="stat"><b>${d.users.length}</b><span>Utilizatori</span></div><div class="stat"><b>${d.listings.length}</b><span>Anunțuri</span></div><div class="stat"><b>${openReports}</b><span>Raportări deschise</span></div><div class="stat"><b>${suspended}</b><span>Suspendați</span></div>`;const rows=d.reported_users.slice(0,6);$('#reportedPreview').innerHTML=rows.length?rows.map(userRowHtml).join(''):'<div class="empty">Nu există utilizatori raportați.</div>';bindUserActions($('#reportedPreview'));}
function userRowHtml(u){const until=u.suspended?`Suspendat până la ${fmt(u.suspended_until)}`:'Activ';return `<div class="admin-row" data-user-row="${u.id}"><div class="main"><b>${esc(u.display_name)} ${u.verified?'<span class="tag green">Verificat</span>':''}</b><span>${esc(u.email||'fără email')} · ${u.listings_count} anunțuri · ${u.reports_count} raportări</span><small>${u.suspended?`<span class="tag red">${esc(until)}</span> ${esc(u.suspension_reason||'')}`:`<span class="tag green">${until}</span>`}</small></div><div class="actions">${u.role==='admin'?'<span class="tag wine">Admin</span>':u.suspended?`<button class="success" data-unsuspend="${u.id}">Deblochează</button>`:`<select class="duration" data-duration="${u.id}"><option value="24">1 zi</option><option value="72">3 zile</option><option value="168" selected>7 zile</option><option value="720">30 zile</option></select><button class="danger" data-suspend="${u.id}">Suspendă</button>`}${u.role!=='admin'?`<button class="ghost" data-verify="${u.id}" data-value="${u.verified?'0':'1'}">${u.verified?'Retrage verificarea':'Marchează verificat'}</button>`:''}</div></div>`;}
function renderUsers(){const d=state.dashboard;if(!d)return;const q=($('#userSearch')?.value||'').trim().toLowerCase();const rows=d.users.filter(u=>!q||`${u.display_name} ${u.email}`.toLowerCase().includes(q));$('#usersList').innerHTML=rows.length?rows.map(userRowHtml).join(''):'<div class="empty">Niciun utilizator găsit.</div>';bindUserActions($('#usersList'));}
function bindUserActions(root){$$('[data-suspend]',root).forEach(b=>b.onclick=()=>suspendUser(b.dataset.suspend,root));$$('[data-unsuspend]',root).forEach(b=>b.onclick=()=>unsuspendUser(b.dataset.unsuspend));$$('[data-verify]',root).forEach(b=>b.onclick=()=>verifyUser(b.dataset.verify,b.dataset.value==='1'));}
async function suspendUser(id,root){const hours=Number($(`[data-duration="${id}"]`,root)?.value||168);const reason=prompt('Motivul suspendării temporare:','Încălcare reguli marketplace');if(!reason)return;try{await adminAction('suspend_user',{user_id:id,hours,reason});toast('Utilizator suspendat.','success');await loadDashboard();}catch(e){toast(e.message,'error');}}
async function unsuspendUser(id){if(!confirm('Reactivezi accesul acestui utilizator?'))return;try{await adminAction('unsuspend_user',{user_id:id});toast('Acces reactivat.','success');await loadDashboard();}catch(e){toast(e.message,'error');}}
async function verifyUser(id,value){try{await adminAction('set_verified',{user_id:id,verified:value});toast(value?'Utilizator verificat.':'Verificare retrasă.','success');await loadDashboard();}catch(e){toast(e.message,'error');}}

function renderReports(){const d=state.dashboard;if(!d)return;const rows=d.reports.filter(r=>r.status!=='resolved');$('#reportsList').innerHTML=rows.length?rows.map(r=>`<div class="admin-row"><div class="main"><b>${esc(r.listing_title)}</b><span>${esc(r.seller_name)} · ${esc(r.seller_email||'')} · motiv: ${esc(r.reason)}</span><small>${fmt(r.created_at)}${r.details?` · ${esc(r.details)}`:''}</small></div><div class="actions"><button class="ghost" data-resolve="${r.id}">Rezolvă</button>${r.listing_id?`<button class="danger" data-admin-delete="${r.listing_id}">Șterge anunțul</button>`:''}${r.seller_id?`<select class="duration" data-duration="${r.seller_id}"><option value="24">1 zi</option><option value="72">3 zile</option><option value="168" selected>7 zile</option><option value="720">30 zile</option></select><button class="danger" data-suspend="${r.seller_id}">Suspendă user</button>`:''}</div></div>`).join(''):'<div class="empty">Nu există raportări deschise.</div>';$$('[data-resolve]',$('#reportsList')).forEach(b=>b.onclick=()=>resolveReport(b.dataset.resolve));$$('[data-admin-delete]',$('#reportsList')).forEach(b=>b.onclick=()=>adminDeleteListing(b.dataset.adminDelete));$$('[data-suspend]',$('#reportsList')).forEach(b=>b.onclick=()=>suspendUser(b.dataset.suspend,$('#reportsList')));}
async function resolveReport(id){try{await adminAction('resolve_report',{report_id:id});toast('Raportare închisă.','success');await loadDashboard();}catch(e){toast(e.message,'error');}}

function listingRowHtml(l){return `<div class="admin-row"><div class="main"><b>${esc(l.title)} ${l.reports_count?`<span class="tag red">${l.reports_count} raportări</span>`:''}</b><span>${esc(l.seller_name)} · ${esc(l.seller_email||'')} · ${esc(l.state)}</span><small>${fmt(l.created_at)}</small></div><div class="actions"><button class="danger" data-admin-delete="${l.id}">Șterge anunțul</button></div></div>`;}
function renderListings(){const d=state.dashboard;if(!d)return;const q=($('#listingSearch')?.value||'').trim().toLowerCase();const rows=d.listings.filter(l=>!q||`${l.title} ${l.seller_name} ${l.seller_email}`.toLowerCase().includes(q));$('#adminListings').innerHTML=rows.length?rows.map(listingRowHtml).join(''):'<div class="empty">Niciun anunț găsit.</div>';$$('[data-admin-delete]',$('#adminListings')).forEach(b=>b.onclick=()=>adminDeleteListing(b.dataset.adminDelete));}
async function adminDeleteListing(id){if(!confirm('Ștergi definitiv acest anunț și fotografiile lui?'))return;try{await adminAction('delete_listing',{listing_id:id});toast('Anunț șters.','success');await loadDashboard();}catch(e){toast(e.message,'error');}}

async function loadEditors(){if(state.role!=='admin')return;const {data,error}=await db.from('newsletter_editors').select('email,created_at,added_by').order('created_at',{ascending:false});if(error){console.error(error);return toast('Nu am putut încărca editorii. Dacă tocmai ai primit rolul de admin, ieși și intră din nou în cont.','error');}state.editors=data||[];renderEditors();}
function renderEditors(){if(state.role!=='admin')return;$('#editorsList').innerHTML=state.editors.length?state.editors.map(e=>`<div class="admin-row"><div class="main"><b>${esc(e.email)}</b><small>Adăugat ${fmt(e.created_at)}</small></div><div class="actions"><button class="danger" data-remove-editor="${esc(e.email)}">Elimină</button></div></div>`).join(''):'<div class="empty">Nu există editori newsletter autorizați.</div>';$$('[data-remove-editor]',$('#editorsList')).forEach(b=>b.onclick=()=>removeEditor(b.dataset.removeEditor));}
async function addEditor(e){e.preventDefault();if(state.role!=='admin')return;const btn=e.currentTarget.querySelector('button'),email=String(new FormData(e.currentTarget).get('email')||'').trim().toLowerCase();setBusy(btn,true,'Se adaugă…');try{const {error}=await db.from('newsletter_editors').insert({email,added_by:state.user.id});if(error)throw error;e.currentTarget.reset();toast('Editor autorizat.','success');await loadEditors();}catch(err){toast(err.code==='23505'?'Emailul este deja autorizat.':err.message,'error');}finally{setBusy(btn,false);}}
async function removeEditor(email){if(!confirm(`Elimini accesul editorial pentru ${email}?`))return;const {error}=await db.from('newsletter_editors').delete().eq('email',email);if(error)return toast(error.message,'error');toast('Acces editorial eliminat.','success');await loadEditors();}

async function loadPosts(){const {data,error}=await db.from('blog_posts').select('id,author_id,author_name,title,slug,excerpt,body,image_path,status,published_at,created_at,updated_at').order('created_at',{ascending:false});if(error){console.error(error);return toast('Nu am putut încărca articolele.','error');}state.posts=data||[];renderPosts();}
function canEditPost(p){return state.role==='admin'||p.author_id===state.user.id;}
function renderPosts(){const root=$('#postsList');if(!root)return;if(!state.posts.length){root.innerHTML='<div class="empty">Nu există încă articole.</div>';return;}root.innerHTML=state.posts.map(p=>`<div class="post-item"><b>${esc(p.title)}</b><span>${p.status==='published'?'<span class="tag green">Publicat</span>':'<span class="tag wine">Ciornă</span>'} · ${esc(p.author_name||'Support Hub')}</span><small>${fmt(p.published_at||p.created_at)}</small>${canEditPost(p)?`<div class="actions"><button class="ghost" data-edit-post="${p.id}">Editează</button><button class="danger" data-delete-post="${p.id}">Șterge</button></div>`:''}</div>`).join('');$$('[data-edit-post]',root).forEach(b=>b.onclick=()=>editPost(b.dataset.editPost));$$('[data-delete-post]',root).forEach(b=>b.onclick=()=>deletePost(b.dataset.deletePost));}
function previewLocalImage(file){if(!file){$('#postImagePreview').hidden=true;return;}const u=URL.createObjectURL(file);$('#postImagePreview').hidden=false;$('#postImagePreview').innerHTML=`<img src="${u}" alt="Previzualizare">`;}
function editPost(id){const p=state.posts.find(x=>x.id===id);if(!p||!canEditPost(p))return;const f=$('#postForm');f.elements.id.value=p.id;f.elements.image_path.value=p.image_path||'';f.elements.title.value=p.title||'';f.elements.excerpt.value=p.excerpt||'';f.elements.body.value=p.body||'';f.elements.status.value=p.status||'published';f.elements.image.value='';$('#postFormTitle').textContent='Editează articolul';$('#savePostBtn').textContent='Salvează modificările';$('#cancelPostEdit').hidden=false;if(p.image_path){$('#postImagePreview').hidden=false;$('#postImagePreview').innerHTML=`<img src="${esc(imageUrl(p.image_path))}" alt="${esc(p.title)}">`;}else $('#postImagePreview').hidden=true;scrollTo({top:0,behavior:'smooth'});}
function resetPostForm(){const f=$('#postForm');f.reset();f.elements.id.value='';f.elements.image_path.value='';f.elements.status.value='published';$('#postFormTitle').textContent='Articol nou';$('#savePostBtn').textContent='Publică articolul';$('#cancelPostEdit').hidden=true;$('#postImagePreview').hidden=true;$('#postImagePreview').innerHTML='';}
async function savePost(e){e.preventDefault();const form=e.currentTarget,btn=$('#savePostBtn'),fd=new FormData(form),editingId=String(fd.get('id')||''),file=form.elements.image.files?.[0];setBusy(btn,true,editingId?'Se salvează…':'Se publică…');let newImagePath=null;try{if(file&&file.size>6*1024*1024)throw new Error('Imaginea poate avea maximum 6 MB.');const id=editingId||crypto.randomUUID();const title=String(fd.get('title')||'').trim(),body=String(fd.get('body')||'').trim(),excerpt=String(fd.get('excerpt')||'').trim()||body.slice(0,240),status=String(fd.get('status')||'published'),oldImage=String(fd.get('image_path')||'')||null;let imagePath=oldImage;if(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');newImagePath=`${state.user.id}/${id}/${crypto.randomUUID()}.${ext}`;const up=await db.storage.from('blog-images').upload(newImagePath,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(up.error)throw up.error;imagePath=newImagePath;}const row={author_id:state.user.id,author_name:state.profile?.display_name||state.user.email?.split('@')[0]||'Support Hub',title,excerpt,body,image_path:imagePath,status};if(editingId){const current=state.posts.find(p=>p.id===editingId);if(!current||!canEditPost(current))throw new Error('Nu poți edita acest articol.');const {error}=await db.from('blog_posts').update(row).eq('id',editingId);if(error)throw error;if(newImagePath&&oldImage&&oldImage!==newImagePath)await db.storage.from('blog-images').remove([oldImage]);}else{row.id=id;row.slug=`${slugify(title)}-${Date.now().toString(36)}`;const {error}=await db.from('blog_posts').insert(row);if(error)throw error;}toast(editingId?'Articol actualizat.':status==='published'?'Articol publicat.':'Ciornă salvată.','success');resetPostForm();await loadPosts();}catch(err){console.error(err);if(newImagePath)await db.storage.from('blog-images').remove([newImagePath]);toast(err.message||'Articolul nu a putut fi salvat.','error');}finally{setBusy(btn,false);}}
async function deletePost(id){const p=state.posts.find(x=>x.id===id);if(!p||!canEditPost(p))return;if(!confirm('Ștergi definitiv acest articol?'))return;try{const {error}=await db.from('blog_posts').delete().eq('id',id);if(error)throw error;if(p.image_path)await db.storage.from('blog-images').remove([p.image_path]);toast('Articol șters.','success');if($('#postForm [name=id]').value===id)resetPostForm();await loadPosts();}catch(e){toast(e.message,'error');}}

init().catch(e=>{console.error(e);deny('Panoul nu s-a inițializat corect.');});
